#!/bin/bash
for name in 강경호 강연우 김동규 김태현 손준혁 이루미 이형주 황해린
do
    git checkout $name
    git pull
    git merge main -m 'main과 합침'
    git add -A
    git reset
    git add -A
    git commit -m "$(date "%Y%m%d") 숙제 추가"
    git push
done
